# Generated by Django 4.2.7 on 2023-12-10 23:54

import auctions.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auction_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='upload',
            field=models.FileField(upload_to=auctions.utils.user_directory_path),
        ),
    ]
