# Generated by Django 4.2.7 on 2023-12-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auction_starting_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='bid_counter',
            field=models.IntegerField(default=0),
        ),
    ]
