# Generated by Django 4.2.7 on 2023-12-13 21:10

import auctions.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='upload',
        ),
        migrations.CreateModel(
            name='ImagesUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('upload', models.FileField(upload_to=auctions.utils.user_directory_path)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_img', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
