# Generated by Django 4.2.7 on 2023-12-16 19:02

import auctions.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_auction_upload_imagesupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesupload',
            name='title',
        ),
        migrations.AddField(
            model_name='imagesupload',
            name='auction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_img', to='auctions.auction'),
        ),
        migrations.AlterField(
            model_name='imagesupload',
            name='upload',
            field=models.FileField(null=True, upload_to=auctions.utils.user_directory_path),
        ),
    ]
