# Generated by Django 4.2.7 on 2023-12-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_bid_bid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='bid_counter',
            field=models.IntegerField(),
        ),
    ]
