# Generated by Django 4.2.7 on 2023-12-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_bid_bid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
