# Generated by Django 4.2.7 on 2023-12-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auction_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='bid_counter',
            field=models.IntegerField(default=0),
        ),
    ]
