# Generated by Django 4.2.7 on 2024-01-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auction_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='close_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='Wishlist_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
