# Generated by Django 4.2.7 on 2024-01-04 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auction_close_date_wishlist_wishlist_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='Wishlist_date',
            new_name='wishlist_date',
        ),
    ]
