# Generated by Django 4.2.7 on 2024-01-04 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_rename_wishlist_date_wishlist_wishlist_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ['creation_date']},
        ),
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['bid_date']},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['wishlist_date']},
        ),
    ]
