# Generated by Django 4.2.7 on 2024-01-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
